title: IT-блог
description: > # this means to ignore newlines until "baseurl:"
  Личный блог автора канала Data Science Guy<br>
#baseurl: "" # the subpath of your site, e.g. /blog
url: "ds-guy.com" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Kirill Burovin'
  last_name: 'Burovin'
  avatar: '/images/avatar.jpg'
  github_username:  kupchanski 
  email: kup9nps@gmail.com
  telegram_name: kupchanski
  logo: '/images/Data Science Guy.png'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


